site_name: Outworkings of God's Love
site_description: My Blog on my thoughts of Life, God and Christianity
theme: readthedocs
nav:
- Home: 'index.md'
- Blog List:
    - 'What is existence: Fundamentals to Christianity': 'existence.md'
    - 'What is Truth: Fundamentals to Christianity': 'truth.md'
    - 'What is Love: Fundamentals to Christianity': 'LOVE.md'
    - 'Love Paradox': 'loveparadox.md'
    - 'Getting out of the Court Room: the Antidote to Legalism': 'legalism.md'
    - 'Psychology, Christianity and the Bible': 'Psychology, Christianity and the Bible.md'
    - 'Vulnerability, Trust, Power': 'vulnerability_trust_power.md'
    - 'Sin': 'sin.md'
    - 'Predestination and Free Will': predestination_free_will.md
- Appendix:
    - Book List: 'booklist.md'
site_author: 'Michael Copeland'